import type { PlaceInput } from '@kodoko/domain';

// Generated by tools/tokyo-events/collect-tokyo-events.mjs.
// Review generated diffs before merging. Only public event data is included.
export const generatedEventPlaces: PlaceInput[] = [
  {
    id: "tokyo-event-1f5caf26e7f53ae3",
    name: "\u3059\u307f\u3060\u307e\u3064\u308a\u30fb\u3053\u3069\u3082\u307e\u3064\u308a",
    category: 'event',
    latitude: 35.6963,
    longitude: 139.8119,
    address: "\u6771\u4eac\u90fd\u58a8\u7530\u533a\u9326\u7cf84-15-1",
    municipalityCode: "13107",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "Date: 10\u6708\u521d\u65ec\u9803. Venue: \u9326\u7cf8\u516c\u5712\u307b\u304b. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://sumidamatsuri.com/",
    sourceUrl: "https://sumidamatsuri.com/",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u58a8\u7530\u533a / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://sumidamatsuri.com/",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-d8e18c3645890054",
    name: "\u5730\u8535\u307e\u3064\u308a",
    category: 'event',
    latitude: 35.7531,
    longitude: 139.4719,
    address: "\u6771\u4eac\u90fd\u6771\u6751\u5c71\u5e02\u91ce\u53e34-6-1",
    municipalityCode: "13213",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 11\u67083\u65e5 - 11\u67083\u65e5. Venue: \u6b63\u798f\u5bfa. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u6771\u6751\u5c71\u5e02 / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-d81f83a724f7e152",
    name: "\u5409\u826f\u796d\u30fb\u5143\u7984\u5e02",
    category: 'event',
    latitude: 35.6982,
    longitude: 139.7986,
    address: "\u6771\u4eac\u90fd\u58a8\u7530\u533a\u4e21\u56fd3-13-9",
    municipalityCode: "13107",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 12\u6708\u9803. Venue: \u5409\u826f\u90b8\u8de1\uff08\u672c\u6240\u677e\u5742\u753a\u516c\u5712\uff09. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.1214.tokyo/p2",
    sourceUrl: "https://www.1214.tokyo/p2",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u58a8\u7530\u533a / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.1214.tokyo/p2",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-f1e2c55e47976de6",
    name: "\u6771\u6751\u5c71\u6625\u306e\u7dd1\u306e\u796d\u5178",
    category: 'event',
    latitude: 35.7558,
    longitude: 139.4722,
    address: "\u6771\u4eac\u90fd\u6771\u6751\u5c71\u5e02\u5bcc\u58eb\u898b\u753a5-4-67",
    municipalityCode: "13213",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 4\u670829\u65e5 - 4\u670829\u65e5. Venue: \u90fd\u7acb \u6771\u6751\u5c71\u4e2d\u592e\u516c\u5712. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u6771\u6751\u5c71\u5e02 / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-bef0ab924512628b",
    name: "\u79cb\u6d25\u795e\u793e\u4f8b\u5927\u796d",
    category: 'event',
    latitude: 35.7399,
    longitude: 139.5099,
    address: "\u6771\u4eac\u90fd\u6771\u6751\u5c71\u5e02\u79cb\u6d25\u753a",
    municipalityCode: "13213",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 7\u670827\u65e5 - 7\u670828\u65e5. Venue: \u79cb\u6d25\u795e\u793e. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u6771\u6751\u5c71\u5e02 / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-223fcbf6131a319b",
    name: "\u9685\u7530\u5ddd\u82b1\u706b\u5927\u4f1a",
    category: 'event',
    latitude: 35.705,
    longitude: 139.8099,
    address: "\u6771\u4eac\u90fd\u58a8\u7530\u533a\u58a8\u7530\u5ddd\u6cbf\u3044",
    municipalityCode: "13107",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 7\u6708\u4e0b\u65ec. Venue: \u9685\u7530\u5ddd. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.sumidagawa-hanabi.com/",
    sourceUrl: "https://www.sumidagawa-hanabi.com/",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u58a8\u7530\u533a / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.sumidagawa-hanabi.com/",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-47479f77c5322394",
    name: "\u8acf\u8a2a\u795e\u793e\u4f8b\u5927\u796d",
    category: 'event',
    latitude: 35.7493,
    longitude: 139.4688,
    address: "\u6771\u4eac\u90fd\u6771\u6751\u5c71\u5e02\u8acf\u8a2a\u753a",
    municipalityCode: "13213",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: 8\u670826\u65e5 - 8\u670827\u65e5. Venue: \u8acf\u8a2a\u795e\u793e. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u6771\u6751\u5c71\u5e02 / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  },
  {
    id: "tokyo-event-5984927466393c47",
    name: "\u6771\u6751\u5c71\u5e02\u6c11\u7523\u696d\u307e\u3064\u308a",
    category: 'event',
    latitude: 35.753,
    longitude: 139.4681,
    address: "\u6771\u4eac\u90fd\u6771\u6751\u5c71\u5e02\u672c\u753a1-2-3",
    municipalityCode: "13213",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    priceLevel: 0,
    strollerFriendly: false,
    shortDescription: "Date: \u958b\u59cb\u65e5 11\u6708\u7b2c2\u571f\u66dc;\u7d42\u4e86\u65e5 11\u6708\u7b2c2\u65e5\u66dc. Venue: \u6771\u6751\u5c71\u5e02\u5f79\u6240\u5468\u8fba. Collected from public Tokyo event data; confirm current details at the official source.",
    websiteUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceUrl: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
    sourceCheckedAt: "2026-08-19T21:39:47.686Z",
    status: 'published',
    provenance: [
      {
        type: 'open-data',
        name: "\u6771\u6751\u5c71\u5e02 / \u30a4\u30d9\u30f3\u30c8\u4e00\u89a7",
        url: "https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_event.csv",
        fetchedAt: "2026-08-19T21:39:47.686Z"
      }
    ]
  }
];
