import type { PlaceInput } from '@kodoko/domain';

// Generated by tools/tokyo-events/collect-tokyo-events.mjs.
// Review generated diffs before merging. Only public event data is included.
export const generatedEventPlaces: PlaceInput[] = [];