import type { PlaceInput } from '@kodoko/domain';

// Generated by tools/tokyo-events/collect-kodomo-events.mjs.
// Source: https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/
// Records all current "期間限定" event cards from the Tokyo Metropolitan children's
// event portal. Coordinates use the host municipality centroid (venue-level
// geocoding pending human review). Review generated diffs before merging.
export const kodomoEventPlaces: PlaceInput[] = [
  {
    id: "kodomo-event-908c689976b8",
    name: "愛知・名古屋2026大会を応援！都庁展望室パブリックビューイング",
    category: 'event',
    latitude: 35.70281,
    longitude: 139.70555,
    eventPeriod: {
      startMonth: 8,
      startDay: 13,
      endMonth: 8,
      endDay: 31
    },
    address: "東京都庁第一本庁舎45階 南展望室（新宿区）",
    municipalityCode: "13104",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'indoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "競泳決勝のパブリックビューイングを、都庁展望室で開催します。8月19日（水）から参加者を募集！都庁から、競泳決勝に挑む選手たちへ熱い声援を届けよう！ 期間: 2026年9月21日（月・祝）. 場所: 東京都庁第一本庁舎45階 南展望室. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-908c689976b8-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/3229f525c35ef30b3c691cff7135cf34a4e33dfa.jpg",
        alt: "愛知・名古屋2026大会を応援！都庁展望室パブリックビューイング",
        cover: true
      }
    ],
    websiteUrl: "https://www.sports-tokyo-info.metro.tokyo.lg.jp/eventblog/2026/2/bm_26022001/publicviewing.html",
    sourceUrl: "https://www.sports-tokyo-info.metro.tokyo.lg.jp/eventblog/2026/2/bm_26022001/publicviewing.html",
    sourceCheckedAt: "2026-08-22T13:36:36.299Z",
    status: 'published'
  },
  {
    id: "kodomo-event-5a52e28b75ff",
    name: "”あしたの東京プロジェクト”親子で楽しむ「江戸東京歴史ツーリズム」参加者募集",
    category: 'event',
    latitude: 35.70527,
    longitude: 139.81209,
    eventPeriod: {
      startMonth: 8,
      startDay: 7,
      endMonth: 9,
      endDay: 11
    },
    address: "両国駅周辺、江戸東京博物館（墨田区）",
    municipalityCode: "13107",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'indoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "江戸時代から続く歴史や文化、アートに触れて、地域の魅力を発見するツアー。ガイドの説明を聞きながら両国駅周辺を街歩き。ツアー内での気づきや学びを共有するワークショップも実施。 期間: 2026年10月10日（土）〜10月12日（月・祝） 10:00〜13:00、14:30〜17:30. 場所: 両国駅周辺、江戸東京博物館. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-5a52e28b75ff-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/189318c190cd5f5dfc85c1c969422978b2591dc3.jpg",
        alt: "”あしたの東京プロジェクト”親子で楽しむ「江戸東京歴史ツーリズム」参加者募集",
        cover: true
      }
    ],
    websiteUrl: "https://tokyotokyo.jp/ja/action/tokyo-tomorrow-project.tokyotokyo.jp/",
    sourceUrl: "https://tokyotokyo.jp/ja/action/tokyo-tomorrow-project.tokyotokyo.jp/",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-ac18c2caa1b4",
    name: "TOKYOデザインマンホールデジタルラリー",
    category: 'event',
    latitude: 35.6922,
    longitude: 139.76121,
    eventPeriod: {
      startMonth: 8,
      startDay: 7,
      endMonth: 3,
      endDay: 31
    },
    address: "東京都内全域（多摩地域・離島地域含む）（千代田区）",
    municipalityCode: "13101",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "スマホ1つで誰でも参加可能！都内のデザインマンホールや観光スポットを巡るラリーに参加して、マンホールグッズをゲットしよう 期間: 〜2027年3月31日（水）まで. 場所: 東京都内全域（多摩地域・離島地域含む）. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-ac18c2caa1b4-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/ffe78cd095c1310ee04a7c128eee38e0a97db3cd.jpg",
        alt: "TOKYOデザインマンホールデジタルラリー",
        cover: true
      }
    ],
    websiteUrl: "https://www.tokyo-manhole.metro.tokyo.lg.jp",
    sourceUrl: "https://www.tokyo-manhole.metro.tokyo.lg.jp",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-40240567b187",
    name: "「いちばの広場」夏休み親子イベント〜親子で学ぶ中央卸売市場〜",
    category: 'event',
    latitude: 35.63524,
    longitude: 139.81001,
    eventPeriod: {
      startMonth: 8,
      startDay: 1,
      endMonth: 8,
      endDay: 22
    },
    address: "豊洲市場及び周辺施設 ※詳しくは、「いちばの広場ナビ」をご覧ください。（江東区）",
    municipalityCode: "13108",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "夏休みに親子でいちばを体験できるイベントを開催します！ 申し込み不要で誰でも参加できるプログラムもあります！ 市場ツアーや料理教室・産地フェア・体験イベントなど楽しいこといっぱい！ 【参加費無料】 期間: 2026年8月21日(金)〜8月22日(土) 開催時間はイベントによって異なります。 事前応募が必要な場合がありますので、詳しくは、「いちばの広場ナビ」をご覧ください。. 場所: 豊洲市場及び周辺施設 ※詳しくは、「いちばの広場ナビ」をご覧ください。. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-40240567b187-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/30f6ae04197b896cfb05d85dfe85def5040558db.jpg",
        alt: "「いちばの広場」夏休み親子イベント〜親子で学ぶ中央卸売市場〜",
        cover: true
      }
    ],
    websiteUrl: "https://central-wholesale-market-pr.com/tanoshimu/summer-event/",
    sourceUrl: "https://central-wholesale-market-pr.com/tanoshimu/summer-event/",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-ce32fd757eee",
    name: "行こう、学ぼう、防災体験",
    category: 'event',
    latitude: 35.70281,
    longitude: 139.70555,
    eventPeriod: {
      startMonth: 8,
      startDay: 1,
      endMonth: 3,
      endDay: 31
    },
    address: "以下の８施設 （池袋防災館、立川防災館、本所防災館、消防博物館、そなエリア東京、しながわ防災体験館、東京都北区防災センター、練馬区立防災学習センター）（新宿区）",
    municipalityCode: "13104",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'indoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "都内国公私立等などの小学生（全学年）及び中学１年生とその保護者が、防災教育デジタル教材「防災ノート〜災害と安全〜」等を通じて防災について学ぶとともに、対象の防災体験施設（都内８か所）で様々な防災体験（地震体験、消火体験等など）を行う。 期間: 2026/7/1（水）〜2027/3/31（水）. 場所: 以下の８施設 （池袋防災館、立川防災館、本所防災館、消防博物館、そなエリア東京、しながわ防災体験館、東京都北区防災センター、練馬区立防災学習センター）. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-ce32fd757eee-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/bosai.png",
        alt: "行こう、学ぼう、防災体験",
        cover: true
      }
    ],
    websiteUrl: "https://www.anzenedu.metro.tokyo.lg.jp/taiken/",
    sourceUrl: "https://www.anzenedu.metro.tokyo.lg.jp/taiken/",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-10afacab268e",
    name: "はっけん！とちょうアドベンチャースタンプラリー",
    category: 'event',
    latitude: 35.70281,
    longitude: 139.70555,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 23
    },
    address: "東京都庁第一本庁舎（新宿区）",
    municipalityCode: "13104",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "都庁舎内のスポットを巡り、都庁の魅力や機能をクイズで学びながらスタンプを集めるイベントを開催します。 条件達成で都星人グッズを贈呈します。 ＶＲバンジージャンプ体験も実施します（定員あり）。 期間: 2026年8月8日（土）〜8月23日（日）10:00〜17:00. 場所: 東京都庁第一本庁舎. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-10afacab268e-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/e5aad83bc4c34c2593259963d806d6042bbfed9b.png",
        alt: "はっけん！とちょうアドベンチャースタンプラリー",
        cover: true
      }
    ],
    websiteUrl: "https://www.zaimu.metro.tokyo.lg.jp/information/topics/r8/tochostamprally",
    sourceUrl: "https://www.zaimu.metro.tokyo.lg.jp/information/topics/r8/tochostamprally",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-c77903ea3c7f",
    name: "東京舞台芸術祭",
    category: 'event',
    latitude: 35.6922,
    longitude: 139.76121,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 11,
      endDay: 3
    },
    address: "東京都全域（プログラムにより異なります。）（千代田区）",
    municipalityCode: "13101",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "東京舞台芸術祭は、東京を国際的な舞台芸術の拠点とすることを目指す都市型の芸術祭です。 演劇やダンスのほかジャンルを横断する作品の上演に加え、舞台芸術をより身近に感じられる体験の場をつくります。 期間: 2026年9月1日〜11月3日. 場所: 東京都全域（プログラムにより異なります。）. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-c77903ea3c7f-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/0a7bbc755da84c5bd03eb4c3c263440d3920fb59.png",
        alt: "東京舞台芸術祭",
        cover: true
      }
    ],
    websiteUrl: "https://tokyofestival.jp/",
    sourceUrl: "https://tokyofestival.jp/",
    sourceCheckedAt: "2026-08-22T13:36:36.302Z",
    status: 'published'
  },
  {
    id: "kodomo-event-201686247eed",
    name: "里海まつり",
    category: 'event',
    latitude: 35.63537,
    longitude: 139.8628,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 30
    },
    address: "葛西海浜公園 西なぎさ（江戸川区）",
    municipalityCode: "13123",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "葛西海浜公園西なぎさにおいて、海水浴体験を開催します。通常は遊泳禁止ですが、この期間については、指定された遊泳ゾーンにて遊泳可能となります。 また、期間中の日曜日、祝日には、NPO法人ふるさと東京を考える実行委員会主催の「里海まつり」として、漁業体験、すいか割り、和船乗船等の各種行事を予定しています。 期間: 2026/7/19〜2026/8/30. 場所: 葛西海浜公園 西なぎさ. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-201686247eed-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/36db17a2ce46b9a6d63ff70cfb1926ebdebfa007.png",
        alt: "里海まつり",
        cover: true
      }
    ],
    websiteUrl: "https://kasaikaihinpark.com/wp-content/uploads/2026/07/2026%E5%B9%B4%E5%BA%A6%E9%87%8C%E6%B5%B7%E3%81%BE%E3%81%A4%E3%82%8A.jpg",
    sourceUrl: "https://kasaikaihinpark.com/wp-content/uploads/2026/07/2026%E5%B9%B4%E5%BA%A6%E9%87%8C%E6%B5%B7%E3%81%BE%E3%81%A4%E3%82%8A.jpg",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-fde96b638cde",
    name: "インラインスケート教室",
    category: 'event',
    latitude: 35.61766,
    longitude: 139.75707,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 30
    },
    address: "大井ふ頭中央海浜公園 さくら広場（品川区）",
    municipalityCode: "13109",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "インラインスケート普及事業である「やしおスケートパーク」の皆様による体験会です。参加費無料、当日さくら広場へお越し下さい。体験会ご参加の方は、長めの靴下と自転車等のヘルメットをご持参ください。（ヘルメットは無料レンタルもございます） 期間: 2026年8月16日（日）・2026年8月23日（日）・2026年8月30日（日） 10:00〜17:00 毎月第1、第3、(第5）の日曜日. 場所: 大井ふ頭中央海浜公園 さくら広場. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-fde96b638cde-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/3cd2e57dad063227115ac086c83a7b31891ba3bc.jpg",
        alt: "インラインスケート教室",
        cover: true
      }
    ],
    websiteUrl: "https://tokyo-south-seaside-parks.com/event/%e3%82%a4%e3%83%b3%e3%83%a9%e3%82%a4%e3%83%b3%e3%82%b9%e3%82%b1%e3%83%bc%e3%83%88%e4%bd%93%e9%a8%93%e4%bc%9a-8%e6%9c%88",
    sourceUrl: "https://tokyo-south-seaside-parks.com/event/%e3%82%a4%e3%83%b3%e3%83%a9%e3%82%a4%e3%83%b3%e3%82%b9%e3%82%b1%e3%83%bc%e3%83%88%e4%bd%93%e9%a8%93%e4%bc%9a-8%e6%9c%88",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-416fff071e81",
    name: "海の森 生きものみっけ",
    category: 'event',
    latitude: 35.63524,
    longitude: 139.81001,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 30
    },
    address: "海の森公園（江東区）",
    municipalityCode: "13108",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "海の森公園に生息する生きものを捕まえた後、図鑑などを使ってどんな生きものなのかを調査しよう！ 何種類の生きものを見つけることができるかな？ ※捕まえた生きものは持ち帰れませんので、最後は逃がします。当日受付・参加費無料 期間: 2026年8月30日（日）10:00〜15:00. 場所: 海の森公園. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-416fff071e81-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/616eb07510ee6c4293eaa0eb8f1488f46f6d10d7.jpg",
        alt: "海の森 生きものみっけ",
        cover: true
      }
    ],
    websiteUrl: "https://uminomoripark.com/event/%e6%b5%b7%e3%81%ae%e6%a3%ae%e3%80%80%e7%94%9f%e3%81%8d%e3%82%82%e3%81%ae%e3%81%bf%e3%81%a3%e3%81%91-2",
    sourceUrl: "https://uminomoripark.com/event/%e6%b5%b7%e3%81%ae%e6%a3%ae%e3%80%80%e7%94%9f%e3%81%8d%e3%82%82%e3%81%ae%e3%81%bf%e3%81%a3%e3%81%91-2",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-e8f6eca72680",
    name: "ヒコーキを飛ばそう！",
    category: 'event',
    latitude: 35.63524,
    longitude: 139.81001,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 29
    },
    address: "海の森公園（江東区）",
    municipalityCode: "13108",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "キットを使って飛行機を組み立て、 海の森公園の広大な自然の中で、空高く飛ばしてみよう！ 期間: 2026年8月29日（土）10:00〜15:00. 場所: 海の森公園. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-e8f6eca72680-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/0c4c69314bd5873f9ac7745b79aa349bd7733df6.jpg",
        alt: "ヒコーキを飛ばそう！",
        cover: true
      }
    ],
    websiteUrl: "https://uminomoripark.com/event/%e7%b4%99%e3%83%92%e3%82%b3%e3%83%bc%e3%82%ad%e3%82%92%e9%a3%9b%e3%81%b0%e3%81%9d%e3%81%86%ef%bc%81",
    sourceUrl: "https://uminomoripark.com/event/%e7%b4%99%e3%83%92%e3%82%b3%e3%83%bc%e3%82%ad%e3%82%92%e9%a3%9b%e3%81%b0%e3%81%9d%e3%81%86%ef%bc%81",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-0322178d0768",
    name: "うみのもりすけをつくろう！",
    category: 'event',
    latitude: 35.63524,
    longitude: 139.81001,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 8,
      endDay: 23
    },
    address: "海の森公園（江東区）",
    municipalityCode: "13108",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "葉っぱや小枝、木の実などで海の森公園のマスコットキャラクター“うみのもりすけ”を作る工作イベント！ 期間: 2026年8月23日（日） 10:00〜12:00、13:30〜15:30. 場所: 海の森公園. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-0322178d0768-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/9840537cb8e3909aebab3036b85c9fdca7000446.jpg",
        alt: "うみのもりすけをつくろう！",
        cover: true
      }
    ],
    websiteUrl: "https://uminomoripark.com/event/%e3%81%86%e3%81%bf%e3%81%ae%e3%82%82%e3%82%8a%e3%81%99%e3%81%91%e3%82%92%e4%bd%9c%e3%82%8d%e3%81%86",
    sourceUrl: "https://uminomoripark.com/event/%e3%81%86%e3%81%bf%e3%81%ae%e3%82%82%e3%82%8a%e3%81%99%e3%81%91%e3%82%92%e4%bd%9c%e3%82%8d%e3%81%86",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-6485aa44ef1c",
    name: "2026みんなのメトポリ夏祭り 〜チャンネル登録者10万人達成！感謝の気持ちを込めて〜",
    category: 'event',
    latitude: 35.61766,
    longitude: 139.75707,
    eventPeriod: {
      startMonth: 7,
      startDay: 1,
      endMonth: 8,
      endDay: 30
    },
    address: "ポリスミュージアム（警察博物館）（品川区）",
    municipalityCode: "13109",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'indoor',
    strollerFriendly: true,
    tags: [
      'stroller-friendly'
    ],
    shortDescription: "チャンネル登録者10万人達成の感謝を込めて、ポリスミュージアム（警察博物館）でパネル展を開催いたします！本展では、メトポリの歴史が分かる展示や、動画で使用した道具の展示、写真スポットをご用意しています。 (事前申込み不要、入館料無料、参加費無料） 期間: 2026年8月1日（土）〜8月30日（日） 9:30〜16:00 ※月曜日は休館日. 場所: ポリスミュージアム（警察博物館）. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-6485aa44ef1c-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/2.event.png",
        alt: "2026みんなのメトポリ夏祭り 〜チャンネル登録者10万人達成！感謝の気持ちを込めて〜",
        cover: true
      }
    ],
    websiteUrl: "https://www.keishicho.metro.tokyo.lg.jp/about_mpd/welcome/welcome/event_metro.html",
    sourceUrl: "https://www.keishicho.metro.tokyo.lg.jp/about_mpd/welcome/welcome/event_metro.html",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-4813508484b2",
    name: "東京都公立学校教員採用スペシャルイベント2026「TOKYO教育Festa！」",
    category: 'event',
    latitude: 35.66988,
    longitude: 139.69961,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 10,
      endDay: 18
    },
    address: "ベルサール渋谷ガーデン ホールA・B・C（渋谷区）",
    municipalityCode: "13113",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "教員のリアルがまとめてわかる1日。 働き方改革の現在地、やりがいや勤務条件などを多角的に理解できるイベントです。 教員に興味のある方はもちろん、進路に悩んでいる方も大歓迎！ 期間: 2026/10/18（日） 10:00〜17:00 （入退場自由）. 場所: ベルサール渋谷ガーデン ホールA・B・C. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-4813508484b2-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/3ff2449660a46ed1e7fe6476da821afea9ba1de2.jpg",
        alt: "東京都公立学校教員採用スペシャルイベント2026「TOKYO教育Festa！」",
        cover: true
      }
    ],
    websiteUrl: "https://www.kyoinsaiyopr.metro.tokyo.lg.jp/event/festa2026.html",
    sourceUrl: "https://www.kyoinsaiyopr.metro.tokyo.lg.jp/event/festa2026.html",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-b4fda7ab27dc",
    name: "中学生・高校生が参加できるボランティア2026",
    category: 'event',
    latitude: 35.6922,
    longitude: 139.76121,
    eventPeriod: {
      startMonth: 7,
      startDay: 31,
      endMonth: 3,
      endDay: 31
    },
    address: "主に都内各地（千代田区）",
    municipalityCode: "13101",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "「ボランティアをはじめてみたいけど、どんな活動があるのかわからない…」。そんな中学生・高校生のみなさんに、さまざまなボランティア活動をご紹介します！ 期間: 2026年6月30日（火）〜2027年3月31日（水）. 場所: 主に都内各地. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-b4fda7ab27dc-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/9843041f0b38eafed63cb5f363ce311b1c14e731.jpg",
        alt: "中学生・高校生が参加できるボランティア2026",
        cover: true
      }
    ],
    websiteUrl: "https://www.vln.metro.tokyo.lg.jp/learn/firststep/130479",
    sourceUrl: "https://www.vln.metro.tokyo.lg.jp/learn/firststep/130479",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  },
  {
    id: "kodomo-event-37e9b3458fa3",
    name: "大田市場親子フラワーアレンジメント教室",
    category: 'event',
    latitude: 35.56263,
    longitude: 139.75331,
    eventPeriod: {
      startMonth: 7,
      startDay: 29,
      endMonth: 8,
      endDay: 25
    },
    address: "大田市場（大田区）",
    municipalityCode: "13111",
    suitableAgeMinMonths: 0,
    suitableAgeMaxMonths: 216,
    indoorOutdoor: 'outdoor',
    strollerFriendly: false,
    tags: [],
    shortDescription: "大田市場で親子フラワーアレンジメント教室を開催！ 初心者の方にもプロが丁寧にお教えします♪ 参加費無料！申し込みはHPから（8月8日まで） 期間: 2026年8月25日（火）13:00〜15:00. 場所: 大田市場. 東京都子ども向けイベントポータルから収録。最新情報は公式サイトでご確認ください。",
    media: [
      {
        id: "kodomo-event-37e9b3458fa3-cover",
        type: 'image',
        url: "https://tokyo-kodomo-hp.metro.tokyo.lg.jp/event/assets/images/90b7ee6204c7319690da940268ff8e977d81d73b.png",
        alt: "大田市場親子フラワーアレンジメント教室",
        cover: true
      }
    ],
    websiteUrl: "https://www.shijou.metro.tokyo.lg.jp/information/topics/2026/07/2026072901",
    sourceUrl: "https://www.shijou.metro.tokyo.lg.jp/information/topics/2026/07/2026072901",
    sourceCheckedAt: "2026-08-22T13:36:36.303Z",
    status: 'published'
  }
];
